name: React Frontend Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-frontend:
    name: Run ESLint on React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for React
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint on React
        working-directory: ./frontend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
